import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";

type Product={id:string;name:string};
type ImageRow={id:string;product_id:string;storage_path:string;alt_text:string|null;sort_order:number;is_primary:boolean};
const url=(path:string)=>supabase.storage.from("product-images").getPublicUrl(path).data.publicUrl;

export default function AdminProductImages(){
 const[products,setProducts]=useState<Product[]>([]),[productId,setProductId]=useState(""),[images,setImages]=useState<ImageRow[]>([]),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 const loadProducts=async()=>{const{data,error}=await supabase.from("products").select("id,name").order("name");if(error)setErr(error.message);else{setProducts(data||[]);if(!productId&&data?.[0])setProductId(data[0].id)}};
 const loadImages=async(id=productId)=>{if(!id){setImages([]);return}const{data,error}=await supabase.from("product_images").select("id,product_id,storage_path,alt_text,sort_order,is_primary").eq("product_id",id).order("sort_order").order("created_at");if(error)setErr(error.message);else setImages((data||[]) as ImageRow[])};
 useEffect(()=>{void loadProducts()},[]);useEffect(()=>{void loadImages()},[productId]);
 async function upload(){if(!productId||!files.length)return;setBusy(true);setErr("");setMsg("");let next=images.length;for(const file of files){const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`products/${productId}/${crypto.randomUUID()}.${ext}`;const up=await supabase.storage.from("product-images").upload(path,file,{upsert:false,cacheControl:"3600",contentType:file.type});if(up.error){setErr(up.error.message);setBusy(false);return}const ins=await supabase.from("product_images").insert({product_id:productId,storage_path:path,alt_text:file.name.replace(/\.[^.]+$/,""),sort_order:next,is_primary:images.length===0&&next===0});if(ins.error){await supabase.storage.from("product-images").remove([path]);setErr(ins.error.message);setBusy(false);return}next++}setFiles([]);setMsg("Image(s) uploaded.");setBusy(false);await loadImages()}
 async function remove(img:ImageRow){if(!confirm("Delete this product image?"))return;const{error}=await supabase.from("product_images").delete().eq("id",img.id);if(error){setErr(error.message);return}await supabase.storage.from("product-images").remove([img.storage_path]);setMsg("Image deleted.");await loadImages()}
 async function primary(img:ImageRow){const first=await supabase.from("product_images").update({is_primary:false}).eq("product_id",productId);if(first.error){setErr(first.error.message);return}const{error}=await supabase.from("product_images").update({is_primary:true}).eq("id",img.id);if(error)setErr(error.message);else{setMsg("Primary image changed.");await loadImages()}}
 return <section className="mx-auto mt-8 max-w-7xl border border-black/10 bg-white p-6"><div><p className="font-mono text-[11px] uppercase tracking-[.18em] text-safety">Supabase Storage + product_images</p><h2 className="mt-1 font-display text-3xl font-semibold uppercase">Product Images</h2><p className="mt-1 text-sm text-smoke">Upload, replace, set primary and delete product images from the dashboard.</p></div>{msg&&<div className="mt-4 border border-green-200 bg-green-50 p-3 text-sm text-green-700">{msg}</div>}{err&&<div className="mt-4 border border-red-200 bg-red-50 p-3 text-sm text-red-700">{err}</div>}<div className="mt-6 grid gap-6 md:grid-cols-[280px_1fr]"><div className="space-y-3"><label className="block text-sm font-medium">Product<select value={productId} onChange={e=>setProductId(e.target.value)} className="field mt-2 w-full"><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="block text-sm font-medium">Images<input type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>setFiles(Array.from(e.target.files||[]))} className="mt-2 block w-full text-sm"/></label>{files.length>0&&<p className="text-xs text-smoke">{files.length} file(s) selected.</p>}<button disabled={busy||!productId||!files.length} onClick={upload} className="w-full bg-black p-3 font-medium text-white disabled:opacity-50">{busy?"Uploading…":"Upload images"}</button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{images.map(img=><article key={img.id} className="border border-black/10 bg-paper p-3"><img src={url(img.storage_path)} alt={img.alt_text||"Product"} className="aspect-square w-full object-contain bg-white"/><div className="mt-2 flex items-center justify-between gap-2 text-xs"><span>{img.is_primary?<b>PRIMARY</b>:`Order ${img.sort_order}`}</span><button onClick={()=>primary(img)} disabled={img.is_primary} className="underline disabled:no-underline disabled:opacity-40">Set primary</button></div><button onClick={()=>remove(img)} className="mt-3 w-full border border-red-200 p-2 text-xs text-red-600">Delete image</button></article>)}{!images.length&&<div className="sm:col-span-2 lg:col-span-4 border border-dashed border-black/20 p-12 text-center text-smoke">Select a product to manage its images.</div>}</div></div></section>;
}
