import { ChangeEvent, useState } from "react";
import { supabase } from "../lib/supabase";
type Row=Record<string,string>;
const required=["name","brand","category"];
const headers=["name","slug","brand","category","subcategory","sku","model_number","short_description","full_description","price","currency","price_type","stock_quantity","availability_status","featured","active","verified","source_url","source_company","specifications"];
function parseCSV(text:string):Row[]{const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const parse=(line:string)=>{const out:string[]=[];let cur="",quote=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'&&line[i+1]==='"'){cur+='"';i++;continue}if(ch==='"'){quote=!quote;continue}if(ch===','&&!quote){out.push(cur.trim());cur=""}else cur+=ch}out.push(cur.trim());return out};const h=parse(lines[0]).map(x=>x.toLowerCase().replace(/\s+/g,"_"));return lines.slice(1).map(line=>{const v=parse(line),r:Row={};h.forEach((k,i)=>r[k]=v[i]||"");return r})}
const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");const bool=(v:string,d=true)=>v===""?d:["true","1","yes","y"].includes(v.toLowerCase());
export default function AdminBulkImport(){
 const[rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState(""),[fileName,setFileName]=useState("");
 function onFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setFileName(file.name);setMsg("");setErr("");const reader=new FileReader();reader.onload=()=>{try{const parsed=parseCSV(String(reader.result||""));setRows(parsed);if(!parsed.length)setErr("No CSV rows found.")}catch{setErr("Could not parse this CSV file.")}};reader.readAsText(file)}
 async function importRows(){if(!rows.length)return;setBusy(true);setErr("");setMsg("");try{const[b,c]=await Promise.all([supabase.from("brands").select("id,name,slug"),supabase.from("categories").select("id,name,slug,parent_id")]);if(b.error)throw b.error;if(c.error)throw c.error;const brandMap=new Map((b.data||[]).map(x=>[x.slug.toLowerCase(),x]));const catMap=new Map((c.data||[]).map(x=>[x.slug.toLowerCase(),x]));const prepared:any[]=[];
  for(let i=0;i<rows.length;i++){const r=rows[i];const missing=required.filter(k=>!r[k]);if(missing.length)throw new Error(`Row ${i+2}: missing ${missing.join(", ")}`);const bs=slugify(r.brand);let brand=brandMap.get(bs);if(!brand){const ins=await supabase.from("brands").insert({name:r.brand,slug:bs,active:true,sort_order:999}).select("id,name,slug").single();if(ins.error)throw ins.error;brand=ins.data;brandMap.set(bs,brand)}const cs=slugify(r.category);let cat=catMap.get(cs);if(!cat){const ins=await supabase.from("categories").insert({name:r.category,slug:cs,active:true,homepage_visible:false,sort_order:999}).select("id,name,slug,parent_id").single();if(ins.error)throw ins.error;cat=ins.data;catMap.set(cs,cat)}let subId=null;if(r.subcategory){const ss=slugify(r.subcategory);let sub=[...catMap.values()].find(x=>x.parent_id===cat!.id&&x.slug===ss);if(!sub){const ins=await supabase.from("categories").insert({name:r.subcategory,slug:ss,parent_id:cat.id,active:true,homepage_visible:false,sort_order:999}).select("id,name,slug,parent_id").single();if(ins.error)throw ins.error;sub=ins.data;catMap.set(`${cat.id}:${ss}`,sub)}subId=sub.id}let specs:any={};if(r.specifications){try{specs=JSON.parse(r.specifications)}catch{throw new Error(`Row ${i+2}: specifications is not valid JSON`)}}prepared.push({name:r.name.trim(),slug:r.slug||slugify(r.name),brand_id:brand.id,category_id:cat.id,subcategory_id:subId,sku:r.sku||null,model_number:r.model_number||null,short_description:r.short_description||null,full_description:r.full_description||null,specifications:specs,price:r.price===""?null:Number(r.price),currency:r.currency||"OMR",price_type:r.price_type||"request_quote",stock_quantity:Number(r.stock_quantity||0),minimum_stock_level:0,availability_status:r.availability_status||"contact_for_availability",featured:bool(r.featured,false),active:bool(r.active,true),verified:bool(r.verified,false),source_url:r.source_url||null,source_company:r.source_company||null})}
  const result=await supabase.from("products").upsert(prepared,{onConflict:"slug"});if(result.error)throw result.error;setMsg(`Imported ${prepared.length} products. Matching slugs were updated.`)}catch(e){setErr(e instanceof Error?e.message:"Import failed.")}finally{setBusy(false)}}
 return <section className="mx-auto mt-8 max-w-7xl border border-black/10 bg-white p-6"><div><p className="font-mono text-[11px] uppercase tracking-[.18em] text-safety">Bulk catalogue ingestion</p><h2 className="mt-1 font-display text-3xl font-semibold uppercase">CSV Product Import</h2><p className="mt-1 max-w-3xl text-sm text-smoke">Upload hundreds or thousands of catalogue rows. Missing brands and categories are created automatically.</p></div>{msg&&<div className="mt-4 border border-green-200 bg-green-50 p-3 text-sm text-green-700">{msg}</div>}{err&&<div className="mt-4 border border-red-200 bg-red-50 p-3 text-sm text-red-700">{err}</div>}<div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="border border-dashed border-black/20 p-6"><input type="file" accept=".csv,text/csv" onChange={onFile} className="block w-full text-sm"/><p className="mt-3 text-xs text-smoke">Headers:</p><code className="mt-2 block break-all bg-paper-2 p-3 text-xs">{headers.join(",")}</code><button disabled={!rows.length||busy} onClick={importRows} className="mt-5 bg-black px-5 py-3 text-sm font-medium text-white disabled:opacity-50">{busy?"Importing…":`Import ${rows.length||0} rows`}</button>{fileName&&<p className="mt-3 text-xs text-smoke">Selected: {fileName}</p>}</div><div className="border border-black/10 bg-paper p-5"><div className="flex items-center justify-between"><h3 className="font-display text-xl font-semibold uppercase">Preview</h3><span className="font-mono text-xs text-smoke">{rows.length} rows</span></div><div className="mt-4 max-h-72 overflow-auto"><table className="w-full min-w-[600px] text-left text-xs"><thead className="bg-paper-2 font-mono uppercase"><tr><th className="p-2">Name</th><th className="p-2">Brand</th><th className="p-2">Category</th><th className="p-2">SKU</th></tr></thead><tbody>{rows.slice(0,20).map((r,i)=><tr key={i} className="border-t border-black/10"><td className="p-2">{r.name}</td><td className="p-2">{r.brand}</td><td className="p-2">{r.category}</td><td className="p-2">{r.sku||"—"}</td></tr>)}</tbody></table>{rows.length>20&&<p className="mt-3 text-xs text-smoke">Showing first 20 rows only.</p>}</div></div></div></section>;
}
